### ISSUE TITLE
recursive itemSpec not working anymore since 2.5.2

### ISSUE THREAD

**Issue by japj** [XpiritBV/Xpirit-Vsts-Build-Pester#8]
It seems pester tests inside subfolders are not executed anymore, this is probably due to fab0fdf38bdb6998c5cbd58b7e48a1fcce178a58 

We discovered this because we have a repository containing multiple folders with tests (related to different modules/scripts) and the tests are not picked up anymore with the wildcard spec "*.tests.ps1" because it is only looking in the root folder.

Any suggestion on how to workaround/fix this?

**Comment by pgroene** [comment]
can you check ** instead of *?

When I have time I'll have a look at it. I had many problems in the past on the ItemSpec. I have to dig into the history to see what exactly broke in the past, I think the change did have some unexpected behaviors. It seems that when choosing one implementation of it breaks stuff when the usage is a little bit different.

Thx for reporting.

**Comment by japj** [comment]
Yes, sorry for the confusion.
It seems **\*.tests.ps1 indeed works correctly, closing this issue
